/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Blender3D (https://sketchfab.com/Blender3D)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/simple-tv-remote-52f142c052564d85b6ef21413af34e25
title: Simple TV Remote
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function Remo({ ...props }) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('simple_tv_remote/scene.gltf')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null} rotation={[Math.PI / 10, 0, 0]} position={[-30, 0, 128]} scale={0.1}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]} scale={0.38}>
          <group name="Remotefbx" rotation={[Math.PI / 2, 0, 0]}>
            <group name="Object_2">
              <group name="RootNode">
                <group name="Armature" position={[0, 50, 10]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                  <group name="Object_5">
                    <primitive object={nodes._rootJoint} />
                    <group name="Object_68" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                    <skinnedMesh name="Object_69" geometry={nodes.Object_69.geometry} material={materials['Scene_-_Root']} skeleton={nodes.Object_69.skeleton} />
                  </group>
                </group>
                <group name="Cube" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('simple_tv_remote/scene.gltf')
